---
title: "RWorksheet#5a_group6(Vicinte, Eusuya, Montealto)"
author: "Group6"
date: "2024-11-18"
output: pdf_document
---

```{r}
install.packages("polite")
install.packages("dplyr")
install.packages("httr")
install.packages("rvest")
```
```{r}
library(polite)
library(dplyr)
library(httr)
library(rvest)
```
```{r}
polite::use_manners(save_as = 'polite_scrape.R')
```
```{r}
url <- 'https://www.amazon.com/s?k=smartphone&crid=39IXJIHHXRLE3&qid=1731928902&sprefix=smartphone%2Caps%2C354&ref=sr_pg_1'

session <- bow(url,
               user_agent = "Educational")
session
```
```{r}
title_list <- scrape(session) %>%
  html_nodes('h2.a-size-mini.a-spacing-none.a-color-base.s-line-clamp-2') %>% 
  html_text
title_list
price <- scrape(session) %>%
  html_nodes('span.a-price-whole') %>% 
  html_text
price
ratings <- scrape(session) %>%
  html_nodes('span.a-size-base.s-underline-text') %>% 
  html_text
ratings

```
```{r}
url2 <- 'https://www.amazon.com/s?k=smartphone&page=2&crid=39IXJIHHXRLE3&qid=1731928557&sprefix=smartphone%2Caps%2C354&ref=sr_pg_2'

session2 <- bow(url2,
               user_agent = "Educational")
session2
```
```{r}
title_list2 <- scrape(session2) %>%
  html_nodes('h2.a-size-mini.a-spacing-none.a-color-base.s-line-clamp-2') %>% 
  html_text
title_list2
```
```{r}
combined_titles <- c(title_list, title_list2)

title_df1 <- data.frame(Title = title_list, stringsAsFactors = FALSE)
title_df2 <- data.frame(Title = title_list2, stringsAsFactors = FALSE)


combined_df <- rbind(title_df1, title_df2)
combined_df
```